Fix broker.go: add missing enableChecksum parameter
compressPacketData signature was changed to include enableChecksum,
but broker.go call wasn't updated. Fixed by passing false for broker
export (--hash flag not supported in broker export yet).

Fixes: Error: not enough arguments in call to compressPacketData